name: Daily Commit

on:
  schedule:
    - cron: '30 19 * * *'  # Runs every day at 7:25 PM UTC
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set git config and commit changes
        run: |
          echo "Daily commit on $(date)" >> daily_log.txt
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add daily_log.txt
          git commit -m "Automated daily commit on $(date)" || echo "No changes to commit"
          git push
        env:
          GITHUB_ACTOR: ${{ github.actor }}
